Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -1,12 +1,70 @@
-name: Test Workflow
+name: Update Playlist
 
 on:
   workflow_dispatch:
+  schedule:
+    - cron: "0 */3 * * *"
+
+permissions:
+  contents: write
 
 jobs:
-  test:
+  update:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Test
-        run: echo "Workflow çalışıyor."
+      - name: Checkout repository
+        uses: actions/checkout@v5
+
+      - name: Build playlist
+        shell: bash
+        run: |
+          echo "#EXTM3U" > playlist.m3u
+
+          urls=(
+            "https://raw.githubusercontent.com/tropicx24-commits/my_channels.m3u/main/playlist.m3u"
+            "https://raw.githubusercontent.com/batuhansabri55/AkcagozTV_Film/main/FilmDizi.m3u"
+            "https://raw.githubusercontent.com/Lonestar1306/iptv-auto-playlists/refs/heads/main/daddylive.m3u"
+          )
+
+          for url in "${urls[@]}"; do
+            echo "Downloading: $url"
+
+            if ! curl -L --fail "$url" -o tmp.m3u; then
+              echo "Failed: $url"
+              continue
+            fi
+
+            awk '
+            /^#EXTINF/{
+              ext=$0
+              getline stream
+              gsub(/\r/, "", stream)
+
+              if(!seen[stream]++){
+                print ext
+                print stream
+              }
+            }
+            ' tmp.m3u >> playlist.m3u
+
+          done
+
+          rm -f tmp.m3u
+
+          echo "Toplam kanal:"
+          grep -c "^#EXTINF" playlist.m3u
+
+      - name: Commit playlist
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+          git add playlist.m3u
+
+          if git diff --cached --quiet; then
+            echo "No changes"
+          else
+            git commit -m "Auto update playlist"
+            git push
+          fi
